version: '3'

services:
  app:
    container_name: project-ruby-crawler
    build:
      context: ./
    volumes:
      - .:/usr/src/app:rw
    tty: true
    environment:
      TZ: Asia/Tokyo
    #restart: unless-stopped
